namespace: "instadock"
name: "instadock"
version: "0.1.0"
readme: "README.md"
authors:
  - "InstaDock Authors (https://www.github.com/instadock/ansible_collection)"
description: "Ansible roles used by instadock project for installing Docker"
dependencies: {}
license:
  - "MIT"
tags:
  - collection
repository: "https://www.github.com/instadock/ansible_collection"
documentation: "http://www.github.com/instadock/ansible_collection"
homepage: "http://www.github.com/instadock/ansible_collection"
issues: "https://www.github.com/instadock/ansible_collection/issues"
