---
- name: 'Upgrade all packages to the latest version'
  dnf:
    name: '*'
    state: latest
  when: upgrade_os

- name: 'Configure SELinux'
  selinux:
    state: "{{ selinux_mode }}"
    policy: "targeted"
  register: selinux_result
  when: selinux_mode is defined

- name: 'Enable EPEL repository'
  dnf:
    state: present
    name:
      - https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ansible_distribution_major_version}}.noarch.rpm

- name: 'DNF Packages'
  dnf:
    state: present
    name:
      - bash-completion # optional
      - curl
      - git
      - iptables-services
      - jq
      - net-tools
      - nfs-utils
      - openssh-clients
      - openssh-server
      - openssl
      - python3-setuptools
      - python3
      - python3-pip
      - python3-virtualenv
      - sudo
      - tmux # optional
      - unzip
      - vim # optional
      - wget
      - yum-plugin-versionlock # TODO: conditional on "version lock" config
      - yum-utils

- name: 'RHEL Specific Packages'
  dnf:
    state: present
    name:
      # chrony needed since systemd-timesyncd is removed from RHEL systemd
      - chrony
  when: ansible_os_family == 'RedHat'

- name: 'Check if reboot is needed'
  shell: needs-restarting -r
  register: reboot_required_shell
  failed_when: false
  changed_when: false

- name: 'Reboot'
  reboot:
  when: reboot_allowed and ( reboot_required_shell.rc != 0 or ( selinux_result.reboot_required is defined and selinux_result.reboot_required ) )

